== DNS-SAFE Project: DNS/DNSSEC {S}ecurity through {A}nalysis, {F}uzzing and {E}xploiting

"`DNS-SAFE`" is an automated test suite that ensures that a nameserver implementation
is security tested through the following aspects:

* Analysis: static and runtime
* Fuzzing: discovering stability issues
* Exploiting: immune to known vulnerabilities


=== Components

The four main areas we test against are (priority according to this order):

* Fuzzing
* Exploiting
* Runtime Analysis
* Static Analysis


=== Targets

While we target all nameserver implementations, (NSD, BIND, Knot, PowerDNS, etc.),
NSD is our initial priority.


=== Fuzzing

"`Retrace`" is a security vulnerability discovery tool:
https://github.com/riboseinc/retrace

This work utilizes "`retrace`" functionality to discover issues in nameserver
implementations through fuzzing.

Retrace modifies the behavior of dynamically-linked ELF (Linux/OpenBSD/FreeBSD/NetBSD) and
Mach-O (macOS) binary executables. It has the ability to change the standard
system calls in a number of different ways. The configuration of Retrace is done
through a ASCII configuration file making it easy to reproduce tests and triggers.
The ASCII configuration file allows for easy scripting in `bash`.

Retrace should be dynamically loaded as a shared library at runtime of the nameserver.

The seed of the Retrace random generator can be controlled with the `fuzzingseed`
option, so that the results are repeatable and reproducable.


==== Fuzz Directions

There are 3 operations of the nameserver that we want to have fuzzed in both IPv4 and IPv6:

* DNSSEC operations (UDP and TCP)
* Zone transfer operations (TCP)
* Name server lookups (UDP)

For each mode, the following areas should be fuzzed:

* Buffer overflows
* Format strings
* DoS (hangs, crashes)
* Information leaks (out of bound reads)
* Memory
* Incomplete I/O


==== Retracing Client Tools

Utilize Retrace on `dig` and `nslookup` to trigger any of the fuzz targets on
the target nameservers. In this scenario we utilize client tools as a vehicle
for our payloads which are injected in valid requests.

We can consider the development of small tools that are identical to `dig` and
`nslookup` but are easier to Retrace due to a smaller footprint.

Retrace is able to inject large strings (`AAAAAAAAAAAA..`), format strings
(`%s%s%s%s..`) and single hex characters of any value `0x00:0xff` into a
variety of network system calls. Any DNS client that establishes a connection
for a query or zone transfer can be retraced and have strings injected.

Retrace string injection should focus on network system calls such as:

1. `write()`
2. `send()`

The string inject modes should include:

1. `INJECT_BUF_OVERFLOW`
2. `INJECT_FORMAT_STR`
3. `INJECT_SINGLE_HEX`

Leverage larger payload packet sizes by using `EDNS0` or completely go through
the 512 byte space (starting at offset 0 to 511) for UDP DNS packets.


==== Retracing Nameservers

Retracing nameservers gives the unique possibility of triggering memory and I/O
faults. In addition arbitrary traffic can be injected in `read()` and `recv()`.


===== String Injection

Not only client tools can be retraced on the network syscalls but also the server side.
The server side could be retraced by using string injection on:

1. `read()`
2. `recv()`

(In case the nameserver has implemented different network system calls then these
will be included as well.)

This will simulate a malicious/malformed client and could potentially trigger a buffer
overflow or format string bug.

The string inject modes (fuzzing type) should include:

1. `INJECT_BUF_OVERFLOW`
2. `INJECT_FORMAT_STR`
3. `INJECT_SINGLE_HEX`

The Retrace configuration for `stringinject` looks like this:
`stringinject,[fuzzingtype],[syscall1]|[syscall2]|[syscallN],[count, hex value]:[offset],[fuzzing rate]`


===== Network Fuzzing

The server side network fuzzing should include `fuzzing-net` for the following syscalls and
fuzzing types with Retrace:

1. `socket()`, `accept()`. Fuzzing type: `NO_MEMORY`, `LIMIT_SOCKET`
2. `connect()`. Fuzzing type: `ADDR_INUSE`, `NET_UNREACHABLE`, `CONN_TIMEOUT`
3. `bind()`, `listen()`. Fuzzing type: `ADDR_INUSE`
4. `send()`, `sendto()`, `sendmsg()`. Fuzzing type: `CONN_RESET, `NO_MEMORY`
5. `recv()`, `recvfrom()`, `recvmsg()`. Fuzzing type: `CONN_REFUSE`, `NO_MEMORY`
6. `gethostbyname()`, `gethostbyaddr()`. Fuzzing type: `HOST_NOT_FOUND`, `SERVICE_NOT_AVAIL`
7. `getaddrinfo()`. Fuzzing type: `HOST_NOT_FOUND`, `SERVICE_NOT_AVAIL`, `NO_MEMORY`

One can run queries through `dnsperf` and allow retrace to crash the server in case
there is no correct check on network error conditions.

The Retrace configuration for `fuzzing-net` looks like this:
`fuzzing-net,[syscall],[fuzzing type],[fuzzing rate]`


===== Memory Fuzzing

The `memoryfuzzing` option in Retrace will cause a percentage of `malloc()`,
`realloc()` and `calloc()` calls to fail. The percentage is specified in a number
(`float`) from `0` (no fail) to `1` (all fail). This is useful to discover places
in the code where return value of allocators are not checked.

The Retrace configuration for `memoryfuzzing` looks like this:
`memoryfuzzing,[fuzzing rate]`


===== Incomplete I/O

The `incompleteio` option in Retrace will cause the `read()` / `write()` calls
to randomly write/read less bytes than was asked. A common scenario that developers
forget to check.

The Retrace configuration for `incompleteio` looks like this:
`incompleteio,[fuzzing rate]`


=== Exploiting

1. Attempting to trigger (known) vulnerabilities remotely.
2. Attempt to bypass access controls.


=== Runtime Analysis

TODO. `valgrind`.


=== Static Analysis

TODO. Such as `Klockwork`.


=== Server Daemon And Monitoring

The nameserver should be started as a docker container (built to run this test
suite). This way we can ensure every single run of the suite is consistent and
results reproducible.

We probably have to build custom containers for different nameserver
implementations to embed our tools.

Server side resources that require monitoring during fuzzing:

* nameserver processes and threads need to be monitored to see whether they
have crashed, hanging or if they are growing indicating a memory leak

* nameserver log files could contain memory addresses (in case of format
strings) or corrupted data (indicating a stack or heap overflow)

* Core dumps of the nameserver process


=== References

* Standcore's open-source https://www.standcore.com/dnsconformance.tgz[DNS conformance testing tool], written by John Levine and Paul Hoffman (who are huge figures in DNS)

* https://docs.menandmice.com/display/MM/DNSSEC+monitoring+tools[Some DNSSEC Monitoring tools]
